version: '3.8'

services:
  cryptobot-pro:
    build: .
    container_name: cryptobot-pro
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./logs:/app/logs
    networks:
      - cryptobot-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN  # Required for Puppeteer
    shm_size: 2gb  # Required for Chrome

  nginx:
    image: nginx:alpine
    container_name: cryptobot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - cryptobot-pro
    networks:
      - cryptobot-network

networks:
  cryptobot-network:
    driver: bridge